namespace: sofia-mosquera-dev
name: backend-mservice

metadata:
  labels:
    app: mi-app-backend

replicaCount: 1

container:
  image: "sofiamosquera/image-backend"
  tag: build-{{ tag }}
  port: 3000
  resources:
    requests:
      cpu: "200m"
      memory: "300Mi"
    limits:
      cpu: "4000m"
      memory: "500Mi"

service:
  type: ClusterIP
  port: 4000

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  host: "postgres-service"
  port: "5432"
  database: "datosdb"
  user: "admin"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "pass123456"
